### ISSUE TITLE
tmpfs noexec problem

### ISSUE THREAD

**Issue by loplex** [megastep/makeself#154] opened 2019-02-01 15:19 UTC
There is error when /tmp is mounted with noexec option. It works for me if I change makeself-header.sh:610 from
`eval "\"\$script\" \$scriptargs \"\\\$@\""; res=\$?`
to
`sh "\"\$script\" \$scriptargs \"\\\$@\""; res=\$?`
But it is not universal

**Comment by realtime-neil** [comment] 2019-02-01 17:38
How might I reproduce this error?

**Comment by loplex** [comment] 2019-02-08 13:00
Mount /tmp with noexec option. I heard it is default in some new linux distributions.

I use this command line to build installer:
`${basedir}/makeself/makeself.sh --header ${basedir}/makeself/makeself-header.sh --nocomp ${installer.loc} ${installer.name} 'Product ${product.version} installation files' ./install.sh ${embedded.tar.file} ${installation.dir.name} ${dir}`

I have already found workaround - use:
`${basedir}/makeself/makeself.sh --header ${basedir}/makeself/makeself-header.sh --nocomp ${installer.loc} ${installer.name} 'Product ${product.version} installation files'` **`sh`** `./install.sh ${embedded.tar.file} ${installation.dir.name} ${dir}`
(my script is executed using 'sh' instead of executing directly using shebang line)

**Comment by realtime-neil** [comment] 2019-02-08 15:53
Ouch. Looks like my `chown +x $(mktemp)` trickery is not long for this world. @megastep does this become a `makeself` problem?

**Comment by megastep** [comment] 2019-02-09 22:44
This could become a serious problem (more of a side effect) considering very often the files will get extracted under `/tmp`; it should be easy to work around for shell scripts and the like by being explicit in how to call them, but could really become a problem for other binary executables...

**Comment by rubicks** [comment] 2019-02-11 20:21
@megastep I don't know how to solve this problem for the general case. With the current code, to play _away_ from `${TMPDIR}` requires user intervention via the `--target` option.

Dodging a `noexec` filesystem seems like a problem that a `makeself` archive has no business solving. Even if it did, the solution would probably be an ugly `switch` block of attempted invocations of the extraction-execution pair, each one failing over to another possible directory location before failing hard with an error. I can imagine (and I'm sure I'm not alone) that this switch block would be a fertile breeding ground for PRs of the form "fallback to `$THIS_DIR` when `$THAT_DIR` is mounted `noexec`".

I dislike assuming things about `$TMPDIR`, but I dislike the potential fixes even more.

**Comment by realtime-neil** [comment] 2019-02-11 20:23
@megastep I don't know how to solve this problem for the general case. With the current code, to play _away_ from `${TMPDIR}` requires user intervention via the `--target` option.

Dodging a `noexec` filesystem seems like a problem that a `makeself` archive has no business solving. Even if it did, the solution would probably be an ugly `switch` block of attempted invocations of the extraction-execution pair, each one failing over to another possible directory location before failing hard with an error. I can imagine (and I'm sure I'm not alone) that this switch block would be a fertile breeding ground for PRs of the form "fallback to `$THIS_DIR` when `$THAT_DIR` is mounted `noexec`".

I dislike assuming things about `$TMPDIR`, but I dislike the potential fixes even more.

**Comment by megastep** [comment] 2019-02-11 21:02
I would tend to agree; while unfortunate it is not exactly something for us to solve directly. I would think that overriding `$TMPDIR` when launching the archive would allow to at least bypass the issue. I really don't want to add more platform-specific code to try to guess if we can actually execute scripts or binaries.

**Comment by realtime-neil** [comment] 2019-02-11 22:03
@loplex, unless you can see a particularly elegant solution to this problem, then I propose this issue be closed with "wontfix".

**Closed** 2019-02-12 03:17 UTC

**Comment by kirbyfan64** [comment] 2019-02-12 04:51
Random thought: what about /run/user/$UID, is that one usually noexec?

**Comment by realtime-neil** [comment] 2019-02-12 11:58
@kirbyfan64 It's not guaranteed by POSIX and even if it were, it's not present in old Unixen.

**Comment by loplex** [comment] 2019-02-13 17:12
> solution

I can't see any elegant solution :(

**Comment by openface** [comment] 2019-04-22 20:21
I'd suggest the addition of `--tmpdir` argument that would set the TMPDIR environment variable at the time `mktemp` is called.   The pkgr project does exactly this for the same reason -- to support systems with /tmp noexec policies.
