### ISSUE TITLE
running with source doesn't work

### ISSUE THREAD

**Issue by uri247** [megastep/makeself#200] opened 2020-03-08 16:05 UTC
Say I've **setup.sh**, a self extract archive. Running setup.sh works fine, as expected.
However, running: `$ source setup.sh` fails, with md5 error.

I'm trying various tricks to create a download-and-run one liner. For example:

```
$ source <(curl -s http://my-web-site/setup.sh)
or
$ curl -s http://my-web-site/setup.sh | sh
```

Any idea why running with source fails? Any idea for a workaround?

**Comment by realtime-neil** [comment] 2020-03-08 19:37
@uri247 , I don't believe makeself supports running from a non-filesystem-resident extraction, but it's not clear to me exactly why.

**Comment by megastep** [comment] 2020-03-08 20:14
It uses $0 to determine the physical location of the archive, so it can run `tail` on it to skip the script at the front to access the actual data. If we can't figure that out (which we couldn't from a pipe) it won't be able to extract.

**Comment by megastep** [comment] 2020-03-09 01:53
This is more or less by design so I'm going to close this issue for now unless somebody comes up with a good workaround for this.

**Closed by megastep** 2020-03-09 01:53 UTC
