### ISSUE TITLE
ARCHIVE_DIR allways returns /usr/bin

### ISSUE THREAD

**Issue by elovin** [megastep/makeself#213] opened 2020-06-02 13:38 UTC
Im using makeself to write a simple installer and I want to copy the self extracting archive itself into the installation path, so I was searching for a way to get the path of the parent directory the archive resides in. Apparently ARCHIVE_DIR is supposed to give me this path but whenever I run echo "$ARCHIVE_DIR" from the entrypoint script I get /usr/bin. 

Im using the latest release 2.4.2.

Am I doing something wrong ?

**Comment by realtime-neil** [comment] 2020-06-02 16:43
@elovin can you supply a reproducer that shows what you're doing and what happens when you do it?

**Comment by elovin** [comment] 2020-06-03 06:39
@realtime-neil
I thought `ARCHIVE_DIR` would give me the path to the self extracting archive created with makeself e.g. when I create a simple archive with makeselfe like this:
`makeself test_dir test.run test ./test.sh` where test.sh only contains `echo "$ARCHIVE_DIR" `
I was under the impression that it would give me the absolute path to the test.run file, instead it gives me /usr/bin (on Arch linux and debian (debian only tested inside a docker container)).

**Comment by megastep** [comment] 2020-06-03 06:41
If you enter that command,  `$ARCHIVE_DIR` will expand to its value in your shell before being passed to Makeself. You cannot use it on the command line, only within the script itself.

**Comment by megastep** [comment] 2020-06-03 06:42
Although `\$ARCHIVE_DIR` might work to prevent it from being substituted by your current shell.

**Comment by elovin** [comment] 2020-06-03 06:46
> If you enter that command, `$ARCHIVE_DIR` will expand to its value in your shell before being passed to Makeself. You cannot use it on the command line, only within the script itself.

Sorry I do not understand, I'm only using it within the startup script ./test.sh, how else am I supposed to use it ?

**Comment by megastep** [comment] 2020-06-03 08:15
Sorry it looks like I misread your command earlier.

From what I can see, `$ARCHIVE_DIR` is basically the result of `dirname $0` inside the script. So it is entirely dependent on the way you call it.

**Comment by elovin** [comment] 2020-06-03 08:30
@megastep would you be willing to execute [this](https://send.firefox.com/download/3ba989225801876e/#XhcwuTniBMn7hnlQwLJDQw) self extracting script and tell me what it prints for you ? 
Its just the test.sh startup script with the `echo "$ARCHIVE_DIR" `line.

**Comment by megastep** [comment] 2020-06-03 08:39
OK, I tried your file and it didn't print anything. However I'm more worried about this at the beginning of your archive:

```
ARCHIVE_DIR=/usr/bin
export ARCHIVE_DIR
```

It really shouldn't be set to this value (likely the location of makeself on your system). It should be `dirname $0` inside the file, I think we might be missing some escaping in `makeself-header.sh`

**Comment by megastep** [comment] 2020-06-03 08:41
I think I just fixed it, will be in the next version or you can use the current branch to try it out.

**Closed by megastep** 2020-06-03 08:41 UTC
